### ISSUE TITLE
When I run yarn run dev after yarn install, the main window goes blank and the console displays the error message

### ISSUE THREAD

**Issue by basilbai** [IroniumStudios/LunarWolf-Browser#100]
**Bug description**
When I run yarn run dev after yarn install, the main window goes blank and the console displays the error message
```
Uncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.
    at <anonymous>:7:24
    at node:electron/js2c/renderer_init:2:16470
    at IpcRendererInternal.<anonymous> (node:electron/js2c/renderer_init:2:10723)
    at IpcRendererInternal.emit (node:events:519:28)
    at Object.onMessage (node:electron/js2c/renderer_init:2:8837)
(anonymous) @ VM113:7
(anonymous) @ node:electron/js2c/renderer_init:2
(anonymous) @ node:electron/js2c/renderer_init:2
emit @ node:events:519
onMessage @ node:electron/js2c/renderer_init:2
```

**To Reproduce**
1.yarn install
2.yarn run build
3.yarn run rebuild
4. yarn run dev || yarn run start

**Expected behavior**
normal startup

**Screenshots**
![image](https://github.com/IroniumStudios/LunarWolf-Browser/assets/26473415/17d30d55-07b0-48b4-bf35-799ecf7c0039)

**Details:**
 - Operating System: Windows 11
 - lunarwolf version: 1.0.1
 - Last known working lunarwolf version: none

**Additional context**

**Comment by IroniumStudios** [comment]
When running all commands make sure that you’re following the steps as provided and nothing else extra so for example, instead of using the outdated yarn dev command just do

yarn install

then yarn build that changes that you have made to the project

but as of right now, I will try reproducing this bug and look into it further

**Comment by IroniumStudios** [comment]
i have found and am working tword a better solution for this issue, as of now i have fixed the problem for now, but this fix wont last
as of beta 2 i have rolled this out
